// This file was generated by counterfeiter
package onebusawayfakes

import (
	"sync"

	"github.com/seattle-beach/go-weatherbus-bus/onebusaway"
)

type FakeClient struct {
	GetStopStub        func(stopID string) (onebusaway.Stop, error)
	getStopMutex       sync.RWMutex
	getStopArgsForCall []struct {
		stopID string
	}
	getStopReturns struct {
		result1 onebusaway.Stop
		result2 error
	}
}

func (fake *FakeClient) GetStop(stopID string) (onebusaway.Stop, error) {
	fake.getStopMutex.Lock()
	fake.getStopArgsForCall = append(fake.getStopArgsForCall, struct {
		stopID string
	}{stopID})
	fake.getStopMutex.Unlock()
	if fake.GetStopStub != nil {
		return fake.GetStopStub(stopID)
	} else {
		return fake.getStopReturns.result1, fake.getStopReturns.result2
	}
}

func (fake *FakeClient) GetStopCallCount() int {
	fake.getStopMutex.RLock()
	defer fake.getStopMutex.RUnlock()
	return len(fake.getStopArgsForCall)
}

func (fake *FakeClient) GetStopArgsForCall(i int) string {
	fake.getStopMutex.RLock()
	defer fake.getStopMutex.RUnlock()
	return fake.getStopArgsForCall[i].stopID
}

func (fake *FakeClient) GetStopReturns(result1 onebusaway.Stop, result2 error) {
	fake.GetStopStub = nil
	fake.getStopReturns = struct {
		result1 onebusaway.Stop
		result2 error
	}{result1, result2}
}

var _ onebusaway.Client = new(FakeClient)
